name: musa-650

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - scikit-learn=1.1.3
  - pip
  - seaborn
  - tensorflow
  - pydot
  - graphviz
  - scikit-image

